config/routes.rb
Pmnews::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :comments
    match '/add_point', to: 'votes#add_point', as: :add_point, via: [:post, :get]
  end

  root 'posts#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  has_ancestry

  validates :body,
            :presence => {:message => "Can't be blank"},
            :length => {:minimum  => 10, :message => "Comment must be more than 10 characters" }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  respond_to :html, :xml, :js

  def new
    @post =Post.friendly.find(params[:post_id])
    @comment = Comment.new(:parent_id => params[:parent_id])
  end

  def show
    @post = Post.friendly.find(params[:post_id])
    @postcomments = Comment.find(params[:parent_id])
    @comment = Comment.new(:parent_id => params[:parent_id])
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comments = @post.comments
    @comment = Comment.new(comment_params)
    @comment.post = @post

    authorize! :create, Comment, message: "You need to be signed up to do that."
    
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    else
      flash[:error] = 'There was an error saving the comment. Please try again.'
      render 'posts/show'
    end
  end

  def update
  end

  def destroy
  end

  def edit
  end

private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id, :parent_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested-comments")
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <ul class="list-inline comment-body">
    <li><%= comment.body %></li>
  </ul>
  <ul class="list-inline comment-info">
    <li>By <%= comment.user.username unless comment.user.nil? %> on <%= comment.created_at.strftime("%D") %></li>
    <li><%= link_to "Reply", post_comment_path(@post, comment, parent_id: comment), id: comment.id, class: "text-info" %></li>
  </ul>
</div>

app/views/comments/_form.html.erb
<!-- Comment form -->
<%= form_for [@post, @comment] do |f| %>
<div class="form-group">
  <%= f.hidden_field :parent_id %>
  <%= f.text_area :body, placeholder: "Leave your comments here...", autofocus: true, class: "form-control" %><br>
  <%= f.submit class: "btn btn-primary" %><br>
</div>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<div class="col-lg-10">
  <h3>New Comment</h3>
  <%= render 'form' %>  
</div>

app/views/comments/show.html.erb
<div class="col-lg-8">
  <%= nested_comments @postcomments.subtree.arrange(:order => :created_at) %>
  
  <%= render 'form' %>

</div>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>