config/routes.rb
Pmnews::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :comments
    match '/add_point', to: 'votes#add_point', as: :add_point, via: [:post, :get]
  end

  root 'posts#index'

  

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  after_save :update_post

  private

  def update_post
    self.post.update_rank  
  end  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :setup
  
  def add_point
    update_vote(1)

    respond_to do |format|
      format.js
      format.html { redirect_to :back}
    end
  end

private

  def setup
    authorize! :create, Vote, message: "You need to be a user to do that."
    @post = Post.friendly.find(params[:post_id])
    @vote = @post.votes.where(user_id: current_user.id).first
  end

  def update_vote(new_value)
    if @vote # if it exists, update it
      @vote.update_attribute(:value, new_value)
    else # create it
      @vote = current_user.votes.create(value: new_value, post: @post)
    end
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_voter.html.erb
<% if user_signed_in?  &&  current_user.votes.where(post_id: post.id).exists? %>
  <%= link_to " ", post_path(post), class: 'fa fa-thumbs-up' %>
<% elsif user_signed_in? && current_user.votes.where(post_id: post.id).nil? %>
  <%= link_to " ", post_add_point_path(post), class: 'fa fa-thumbs-o-up', remote: true, id: post.id %>
<% else %>
  <%= link_to " ", post_add_point_path(post), class: 'fa fa-thumbs-o-up', id: post.id %>
<% end %>

app/views/votes/add_point.js.erb
$("#<%= @post.id %>").attr('class', 'fa fa-thumbs-up');
$("#post-<%= @post.id %>-points").html('<%= escape_javascript @post.points.to_s %> <%= escape_javascript "point".pluralize(@post.points) %>');

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>