config/routes.rb
Pmnews::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts do
    resources :comments
    match '/add_point', to: 'votes#add_point', as: :add_point, via: [:post, :get]
  end

  root 'posts#index'

  

end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="footer">
      <div class="row">
        <div class="col-lg-1">
          <ul class="list-group">
            <a href="facebook.com"><li><i class="fa fa-facebook-square"></i>Facebook</li></a>
            <a href="twitter.com"><li><i class="fa fa-twitter-square"></i>Twitter</li></a>
            <a href="twitter.com"><li><i class="fa fa-google-plus-square"></i>Google+</li></a>
            <a href="twitter.com"><li><i class="fa fa-bitcoin"></i>Donate</li></a>
          </ul>
        </div>
        <div class="col-lg-1">
          <ul class="list-unstyled">
            <li><%= link_to "Submit Post", new_post_path %></li>
          </ul>
        </div> 
      </div>
      <div>&copy 2014 PM-News</div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/"><%= image_tag("pm_news_logo.png", :class => "navbar-image") %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Submit Post", new_post_path %></li>
        <li><%= link_to "Site Rules", new_post_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      <% if user_signed_in? %>
        <li><a href="<%= edit_user_registration_path %>">Signed in as <%= current_user.username %></a></li>
        <li class="dropdown"></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Create Account", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PM News</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
  <%= render partial: 'layouts/navbar'%>
  <div class="container-fluid content">
    <%= render partial: 'layouts/messages', flash: flash %>
    <div class="row">
      <%= yield %>  
    </div>
  </div>
  <%= render partial: 'layouts/footer'%>
</body>
</html>